### ISSUE TITLE
edit and update actions for the format.json?

### ISSUE THREAD

**Issue by timfong888** [nakajima/better-edit-in-place#3]
Just wanted to make sure that the way it works was it needed the edit and update actions respond_to JSON in the controller (versus index)....is that correct?

**Comment by nakajima** [comment]
You got it. If that doesn't work, let me know.

**Comment by timfong888** [comment]
Hmm...the helper works out, and the javascript loads (I have it load last), but the element isn't clickable:

Here's how it renders:

<span rel="/emails/1" id="email_1_days" class="editable">7</span>

emails is the model, days is the attribute, and 1.  This is done in a nested view for campaigns, where campaign has_many :emails....did I miss something?

It's pretty sweet, though...way better than the other plugin...

**Comment by timfong888** [comment]
<code>
 rel="/emails/1" id="email_1_days" class="editable">7
</code>

**Comment by timfong888** [comment]
hmm, trying to render the code..but it is formatting as HTML...
